// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.p2phost.pb;

public interface ConnectReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.ConnectReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated string addrs = 2;</code>
   */
  java.util.List<String>
      getAddrsList();
  /**
   * <code>repeated string addrs = 2;</code>
   */
  int getAddrsCount();
  /**
   * <code>repeated string addrs = 2;</code>
   */
  String getAddrs(int index);
  /**
   * <code>repeated string addrs = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddrsBytes(int index);
}
