// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.p2phost.pb;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Empty)
    com.google.protobuf.MessageOrBuilder {
}
