// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.p2phost.pb;

public interface SendMsgRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SendMsgResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   */
  com.google.protobuf.ByteString getValue();
}
