// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.p2phost.pb;

public interface StringListMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.StringListMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string values = 1;</code>
   */
  java.util.List<String>
      getValuesList();
  /**
   * <code>repeated string values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated string values = 1;</code>
   */
  String getValues(int index);
  /**
   * <code>repeated string values = 1;</code>
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
